- config/routes.rb
- lib/cm_admin.rb
- lib/cm_admin/model.rb
This will add the CRUD routes for models specified and controllers gets defined with namespace CmAdmin.
The block in model has not yet been executed. Still has to find a way.
This commit will allow further developement as basic routes are still available.
> added basic routes and defined controllers

- lib/cm_admin/model.rb
```
cm_admin do
actions only: :index
custom_action 'submit', 'post' do
def blog_submit
puts :hello
end
end
end
```
This works now. Haven't rebased with Anbu's changes
> Executed blocks with respect to CmModel

- Gemfile
- Gemfile.lock
- app/controllers/cm_admin/application_controller.rb
- app/views/cm_admin/main/_cm_pagy_nav.html.slim
- app/views/cm_admin/main/_table.html.slim
- cm_admin.gemspec
- lib/cm_admin.rb
- lib/cm_admin/model.rb
- Slim support added inside the gem
- Pagy gem added inside the gem.
- Basic pagination on index page working
> Index page

- app/views/cm_admin/main/_filters.html.slim
- app/views/cm_admin/main/index.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/filter.rb
Functionality for the filter is pending. On the view, only the search filter will be shown.
> Filter DSL

- Gemfile.lock
- cm_admin.gemspec
- lib/cm_admin/model.rb
- lib/cm_admin/models/form_field.rb
- lib/cm_admin/version.rb
- lib/cm_admin/view_helpers/form_helper.rb
- Edit and new form field added
- Yet to add format option for it.
> Form dsl integration

- app/javascript/packs/cm_admin/application.js
- app/javascript/packs/cm_admin/scaffolds.js
- app/views/layouts/_left_sidebar_nav.html.slim
- app/views/layouts/_quick_links.html.slim
- lib/cm_admin/models/field.rb
- lib/cm_admin/view_helpers.rb
- lib/cm_admin/view_helpers/field_display_helper.rb
- lib/cm_admin/view_helpers/form_field_helper.rb
- lib/cm_admin/view_helpers/navigation_helper.rb
- Renamed the ShowFieldHelper to FormDisplayHelper
> fix: Adding support to precision, custom link and custom_method.

- app/helpers/cm_admin/custom_helper.rb
- app/views/cm_admin/main/_table.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/column.rb
- lib/cm_admin/models/export.rb
- lib/cm_admin/view_helpers/field_display_helper.rb
- Custom helper support
- Renaming the column_type to field_type in column.rb, db_column_name to field_name
> Index association

- app/views/cm_admin/main/index.html.slim
- lib/cm_admin/model.rb
**Problem:** On applying filters error is thrown. Screenshot of the error 👇🏻 
**Solution:** Duplicate methods are present for filtering the data that are removed. The filter method is refactored to make it work in show pages for which additional arguments are added which were missing in the `filter_by` method called via the index page.
> Fix for filters

- app/assets/stylesheets/cm_admin/base/quicksearch.scss
- app/javascript/packs/cm_admin/application.js
- app/javascript/packs/cm_admin/filters.js
- app/javascript/packs/cm_admin/quick_search.js
- app/views/layouts/_quick_links.html.slim
- lib/cm_admin/view_helpers/filter_helper.rb
- lib/cm_admin/view_helpers/navigation_helper.rb
- Some improvement made to filter. 
- I tried to re use the dropdown search filter, But created new function instead later. We can merge later if both can be made common.
> fix: Quick link search and select and redirect

- README.md
- app/views/cm_admin/main/_table.html.slim
- lib/cm_admin/version.rb
- Hardcoded -  Redirection to show page
- Version change
> chore: Updating readme

- app/views/cm_admin/main/_associated_table.html.slim
- app/views/cm_admin/main/_top_navbar.html.slim
- app/views/cm_admin/main/associated_index.html.slim
- app/views/layouts/_custom_action_modals.html.slim
- app/views/layouts/cm_admin.html.slim
- config/routes.rb
- lib/cm_admin/model.rb
- lib/cm_admin/models/action.rb
- lib/cm_admin/models/dsl_method.rb
- lib/cm_admin/view_helpers/page_info_helper.rb
- Custom action, page, tab were dependent on action. So adding few more attr_accessor to differentiate the FE.
- display_type - page, modal, button mostly for custom action usage
> Custom page integration

- lib/cm_admin/model.rb
- lib/cm_admin/models/controller_method.rb
- lib/cm_admin/models/dsl_method.rb
- lib/cm_admin/view_helpers/page_info_helper.rb
- Nested show variable added
- Show page title fixes
- Nested form fixes
- layout_type added to custom action, so same header can be added to nested custom pages.
> fix: Custom page bug fixes

- app/assets/stylesheets/cm_admin/scaffold.scss
- app/views/cm_admin/main/_associated_table.html.slim
- app/views/cm_admin/main/_nested_fields.html.slim
- app/views/cm_admin/main/_nested_table_form.html.slim
- app/views/layouts/_custom_action_modals.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/view_helpers/navigation_helper.rb
- Minor nested cocoon UI changes added
> feat: Visible on sidebar option added

- README.md
- lib/generators/cm_admin/install_generator.rb
- lib/generators/cm_admin/templates/cm_admin_initializer.rb
[Related issue](https://github.com/commutatus/cm-admin/issues/112)
- Generator related files were missing, Generator for failing for new projects.
- Added it back. Yet to test more
> Adding initializer files

- app/views/cm_admin/main/index.html.slim
- lib/cm_admin/models/dsl_method.rb
- Instead of table, we can render partial
> fix: Partial support for index page

- Gemfile
- Gemfile.lock
- README.md
- app/assets/stylesheets/cm_admin/base/scaffold.scss
- app/assets/stylesheets/cm_admin/components/_drawer.scss
- app/assets/stylesheets/cm_admin/scaffold.scss
- app/controllers/cm_admin/application_controller.rb
- app/policies/application_policy.rb
- app/views/cm_admin/main/_associated_table.html.slim
- app/views/cm_admin/main/_tabs.html.slim
- app/views/cm_admin/main/index.html.slim
- app/views/cm_admin/static/dashboard.html.slim
- app/views/cm_admin/static/error_403.html.slim
- cm_admin.gemspec
- config/initializers/active_record_extension.rb
- config/routes.rb
- lib/cm_admin.rb
- lib/cm_admin/configuration.rb
- lib/cm_admin/model.rb
- lib/cm_admin/models/action.rb
- lib/cm_admin/models/controller_method.rb
- lib/cm_admin/models/dsl_method.rb
- lib/cm_admin/models/field.rb
- lib/cm_admin/version.rb
- lib/cm_admin/view_helpers/field_display_helper.rb
- lib/cm_admin/view_helpers/form_helper.rb
- lib/cm_admin/view_helpers/navigation_helper.rb
- lib/cm_admin/view_helpers/page_info_helper.rb
- lib/generators/cm_admin/install_generator.rb
- lib/generators/cm_admin/templates/cm_admin_initializer.rb
- Install generator fixes
- UI related changes
- Partial support added for the index page
- Basic Authorization DSL added, requires improvement
- CodeImprovement - Configuration class added inside the cm_admin module.
> Version 0.5.8 release

- app/helpers/cm_admin/application_helper.rb
- app/views/cm_admin/main/_table.html.slim
- app/views/cm_admin/main/_top_navbar.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/action.rb
- lib/cm_admin/models/controller_method.rb
- lib/cm_admin/models/dsl_method.rb
- lib/cm_admin/version.rb
- lib/generators/cm_admin/install_generator.rb
- lib/generators/cm_admin/policy_generator.rb
- lib/generators/cm_admin/templates/application_policy.rb
- lib/generators/cm_admin/templates/policy.rb
- removed support for accessible_by
- Removed codes related to accessible_by
- Install generator copies application policy
- Policy generator generates policy based on the modal actions
> feat(user-permission): Permission DSL changed

- app/views/cm_admin/main/_table.html.slim
- app/views/cm_admin/main/_tabs.html.slim
- app/views/cm_admin/main/_top_navbar.html.slim
- config/routes.rb
- lib/generators/cm_admin/install_generator.rb
- Custom action in index page error fix
- Profile tab missing in show page fixed
- New page throwing error in development fix
> fix: Custom action fixes

- app/assets/stylesheets/cm_admin/base/table.scss
- app/views/cm_admin/main/_associated_table.html.slim
- app/views/cm_admin/main/_table.html.slim
- app/views/layouts/_cm_flash_message.html.slim
- app/views/layouts/cm_admin.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/action.rb
- lib/cm_admin/models/dsl_method.rb
- lib/cm_admin/view_helpers/form_field_helper.rb
- Placeholder for input boxes
- custom action icon added
- Flash added for custom and create actions
- Commented checkbox, since bulk action is not available now.
- Flash message fixes
- Redirection for create and update
- Dropdown shown if the action is present for nested or associated pages
> fix: Minor HTML fixes

- app/assets/stylesheets/cm_admin/components/_status-tag.scss
- lib/cm_admin/models/column.rb
- lib/cm_admin/view_helpers/field_display_helper.rb
- Support for mapping enum value with custom class added
> fix: tag class option added

- app/controllers/cm_admin/exports_controller.rb
- app/javascript/packs/cm_admin/application.js
- app/javascript/packs/cm_admin/exports.js
- app/views/cm_admin/main/_associated_table.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/export.rb
[CMAD-92](https://commutatus.atlassian.net/browse/CMAD-92)
When exporting data, there were two problems
- Selected columns not getting exported
- Filtered data not getting exported.
> Export issues

- app/controllers/cm_admin/exports_controller.rb
- app/javascript/packs/cm_admin/application.js
- app/javascript/packs/cm_admin/exports.js
- app/javascript/packs/cm_admin/scaffolds.js
- app/views/cm_admin/main/_associated_table.html.slim
- app/views/cm_admin/main/_nested_table_form.html.slim
- app/views/cm_admin/main/show.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/export.rb
- lib/cm_admin/models/field.rb
- lib/cm_admin/version.rb
- lib/generators/cm_admin/install_generator.rb
- lib/generators/cm_admin/policy_generator.rb
- lib/generators/cm_admin/templates/cm_admin_initializer.rb
- lib/generators/cm_admin/templates/policy.rb
- yarn.lock
https://github.com/commutatus/cm-admin/pull/163
https://github.com/commutatus/cm-admin/pull/165
https://github.com/commutatus/cm-admin/pull/167
> Master: Version 0.6.6 releasedd

- README.md
- lib/cm_admin/view_helpers/field_display_helper.rb
> Master - Version 0.6.9 release

- app/views/cm_admin/main/_top_navbar.html.slim
- lib/cm_admin/version.rb
- lib/generators/cm_admin/policy_generator.rb
- lib/generators/cm_admin/templates/policy.rb
[CMAD-98](https://commutatus.atlassian.net/browse/CMAD-98)
Issue ID
https://github.com/commutatus/cm-admin/issues/178
- Page Redirect URL fix. New and edit page links where wrong.
- Policy generator fix
- Previously new and edit links where failing if the model name where like `ZoomRegistratrion` since we used downcase the links were not properly generated.
- Used the path from the cm_admin engine instead of helper
> fix: Policy generator fix and URL for new and edit page fix

- app/javascript/packs/cm_admin/scaffolds.js
- lib/cm_admin/view_helpers/form_field_helper.rb
[UN-861](https://commutatus.atlassian.net/browse/UN-861)
- Date format was shown like YY-MM-DD
- Changed this to "DD-MM-YY"
- Date range and date only needs to be fixed later
> fix: Date formatting issue

- app/views/cm_admin/main/_associated_table.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/controller_method.rb
- lib/cm_admin/models/form_field.rb
- lib/cm_admin/view_helpers/form_field_helper.rb
- lib/cm_admin/view_helpers/form_helper.rb
[MYCN-983](https://commutatus.atlassian.net/browse/MYCN-983)
[UN-824](https://commutatus.atlassian.net/browse/UN-824)
- Nested page creation possible
- Redirection to the same page after submission
- Supports has_many, has_many through, polymorphic
> fix: Creation of records for associated pages

- app/views/cm_admin/main/_table.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/models/controller_method.rb
- lib/cm_admin/view_helpers/page_info_helper.rb
[MYCN-983](https://commutatus.atlassian.net/browse/MYCN-983)
Added Deploy Button on cm-admin index page.
It was needed so the admin and destroy records.
We used a similar approach to edit. We used the delete method in the link generated which call the destroy method. The destroy method destroy the ar_object. After the operation, we redirect the user to the index page.
Done in Climber project.
Working in Rails 6.1.5
Index page:
Logs:
> Added Destroy button in cm-admin

- Gemfile
- Gemfile.lock
- app/controllers/cm_admin/application_controller.rb
- app/controllers/cm_admin/resource_controller.rb
- app/javascript/packs/cm_admin/application.js
- cm_admin.gemspec
- lib/cm_admin/model.rb
- lib/cm_admin/view_helpers/field_display_helper.rb
- package-lock.json
- package.json
- yarn.lock
[CMAD-106](https://commutatus.atlassian.net/browse/CMAD-106)
- Local time support added
- Made improvement to application controller
- Since application controller can be overwritten, the include module(pagy and other) will work from resource controller.
> Local time support

- app/views/cm_admin/main/_show_section.html.slim
- lib/cm_admin/models/row.rb
- lib/cm_admin/view_helpers/field_display_helper.rb
Enable use to wrap fields inside row column layout.
So we can have a row column layout for fields inside a section
> feat: Wrap field inside row layout

- .github/workflows/release-gem.yml
This PR brings in automation to release gems via Github Actions
Improve developer experience
https://github.com/commutatus/cm-admin/actions/runs/9542631429
Several experiments were done on another branch, we are releasing good gems there!
Connected an existing project to the gem released.
> ci: release gem

- app/controllers/cm_admin/resource_controller.rb
- lib/cm_admin/model.rb
- lib/cm_admin/models/action.rb
- lib/cm_admin/models/dsl_method.rb
- redirect after creating or update
- need custom redirect URL after creating or updating.
- update the dsl method for new and edit to take redirect_to as argument which will be lambda.
- added condition in `resource_responder` method to redirect to custom URL if present.
- added routes helper in the model.
https://github.com/commutatus/cm-admin/assets/68422113/0ff72299-8aa9-435c-81d3-4e467bf5340d
> infra: redirect after create or update

- app/controllers/cm_admin/resource_controller.rb
- app/views/cm_admin/main/_nested_table_form.html.slim
- lib/cm_admin/view_helpers/field_display_helper.rb
- lib/cm_admin/view_helpers/form_field_helper.rb
- JSON response with jbuilder
- Attachment improvement for video preview with Not available image
- Title changes in cocoon
- Improvement to JSON response
> Json response

- app/assets/stylesheets/cm_admin/dependency/bootstrap/scss/forms/_form-select.scss
- read-only select
- Search for select with the read-only attribute in CSS, remove the action, and change the background.
> update: readonly select

- app/assets/stylesheets/cm_admin/dependency/bootstrap/scss/forms/_form-select.scss
- remove unnecessary class from selector
- not working when a new field is added by the `add_new` button.
> fix: remove unnecessary class from selector

- app/assets/stylesheets/cm_admin/base/auth.scss
- app/assets/stylesheets/cm_admin/base/cardView.scss
- app/assets/stylesheets/cm_admin/base/comments.scss
- app/assets/stylesheets/cm_admin/base/common.scss
- app/assets/stylesheets/cm_admin/base/filters.scss
- app/assets/stylesheets/cm_admin/base/form.scss
- app/assets/stylesheets/cm_admin/base/kanban.scss
- app/assets/stylesheets/cm_admin/base/navbar.scss
- app/assets/stylesheets/cm_admin/base/quicksearch.scss
- app/assets/stylesheets/cm_admin/base/scaffold.scss
- app/assets/stylesheets/cm_admin/base/show.scss
- app/assets/stylesheets/cm_admin/base/sidebar.scss
- app/assets/stylesheets/cm_admin/base/table.scss
- app/assets/stylesheets/cm_admin/cm_admin.css.scss
- app/assets/stylesheets/cm_admin/components/_accordion.scss
- app/assets/stylesheets/cm_admin/components/_alerts.scss
- app/assets/stylesheets/cm_admin/components/_buttons.scss
- app/assets/stylesheets/cm_admin/components/_status-tag.scss
- app/assets/stylesheets/cm_admin/pages/history_page.scss
- app/assets/stylesheets/cm_admin/pages/import_page.scss
- app/assets/stylesheets/cm_admin/scaffold.scss
- remove unnecessary bootstrap import
- due to unnecessary bootstrap import, CSS size was increasing.
- removed unnecessary bootstrap import and had one import instead.
> fix: remove unnecessary bootstrap import

- app/views/cm_admin/main/_card.html.slim
- app/views/cm_admin/main/_table.html.slim
- app/views/cm_admin/main/_top_navbar.html.slim
- lib/cm_admin/model.rb
- lib/cm_admin/view_helpers/navigation_helper.rb
add display name in model.
- we want a custom display name for a model. 
- add a new field `display_name` in model.
- display `display_name` if present otherwise display default model name.
https://github.com/commutatus/cm-admin/assets/68422113/13962943-4a4f-4a94-881a-1c6f54dc900a
> upadte: add display name in model

- lib/cm_admin/models/field.rb
- show label fix
- no default value for label in show field.
- add a default value for label in show field.
> fix: show label fix

- cm_admin.gemspec
- lib/cm_admin/models/dsl_method.rb
- lib/cm_admin/models/row.rb
- lib/cm_admin/models/section.rb
- lib/cm_admin/view_helpers/form_helper.rb
**Changes Made**
- Added html_attrs to cm_section
- Code Refactor by Robocop
> feat: PRO-5509: Added html_attrs to cm_section

- lib/cm_admin/models/dsl_method.rb
- lib/cm_admin/models/section.rb
- lib/cm_admin/view_helpers/form_helper.rb
Passing html_attrs to row
To tamper issues with row
> fix:Passed html_attrs to row in dsl

- .github/workflows/deploy-yard-docs.yml
- Gemfile
- Gemfile.lock
- cm_admin.gemspec
- lib/cm_admin/models/dsl_method.rb
- add yard doc for dsl methods
- need documentation for dsl methods.
- installed `yard` gem.
- added yard doc comments on each method for dsl method
> feat: add yard doc for dsl methods

- .github/workflows/deploy-yard-docs.yml
> fix: add artifact name

- .github/workflows/deploy-yard-docs.yml
> fix: change action version

- lib/cm_admin/models/dsl_method.rb
> fix: method name

- CNAME
> infra: add cname file

- .github/workflows/deploy-yard-docs.yml
- app/assets/stylesheets/cm_admin/components/_input.scss
- app/controllers/cm_admin/resource_controller.rb
- lib/cm_admin/models/row.rb
- lib/cm_admin/view_helpers/form_field_helper.rb
- lib/cm_admin/view_helpers/form_helper.rb
- Adds label to checkbox and switch button.
- To implement on mynvax
> fix: Checkbox and switch label added

- README.md
> infra: update readme deployement

- Gemfile.lock
- cm_admin.gemspec
> fix: reomve yard from dependency

- lib/cm_admin/models/dsl_method.rb
- add better examples for docs
> update: add better examples

- app/assets/javascripts/cm_admin/form_validation.js
- lib/cm_admin/models/form_field.rb
- lib/cm_admin/view_helpers/form_field_helper.rb
- lib/cm_admin/view_helpers/form_helper.rb
- add multiple check box field, fix label for checkbox and switch and fix radio button
- to follow cm admin design style
- add a new field `multi_check_box`.
- change labels for checbox and switch, to inline.
- fix radio button hardcoded name
https://github.com/user-attachments/assets/5047e704-16b6-4caa-a8b8-109c24cf8dab
> update: add multiple check box field and fix radio button

- app/assets/javascripts/cm_admin/filters.js
- Multi select filter issue fix
When two multi select filter is applied, only the latest one got applied.
https://videos.commutatus.com/videos/cmadmin-multi-select-issue
> fix: Multiple multi select issue fix

- .github/workflows/deploy-yard-docs.yml
- .yardopts
- yard docs deploy with bump gem action
- add yardopts file for yard configuration
> infra: yard docs deploy with bump gem action
